<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class InstansiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataInstansi = [
            [
                'nama' => 'Sekretariat Daerah',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Sekretariat Daerah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Tata Pemerintahan',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Tata Pemerintahan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Sumber Daya Alam',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Sumber Daya Alam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Bina Mental Spiritual dan Kemasyarakatan',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Bina Mental Spiritual dan Kemasyarakatan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Kerjasama',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Kerjasama.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Layanan Pengadaan Barang dan Jasa',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Layanan Pengadaan Barang dan Jasa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Perekonomian',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Perekonomian.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Administrasi Pembangunan',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Administrasi Pembangunan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Organisasi',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Organisasi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Hukum',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Hukum.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Umum',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Umum.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Protokol dan Komunikasi Pimpinan',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Protokol dan Komunikasi Pimpinan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bagian Perencanaan dan Keuangan',
                'telepon' => '(0727) 322070, 322068, 322069, 322300',
                'alamat' => 'Jalan Zainal Abidin Pagar Alam No. 1, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Bagian Perencanaan dan Keuangan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Inspektorat',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Inspektorat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Perencanaan Pembangunan Daerah',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Badan Perencanaan Pembangunan Daerah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Kesatuan Bangsa dan Politik',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Badan Kesatuan Bangsa dan Politik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Penanggulangan Bencana Daerah',
                'telepon' => 'N/A',
                'alamat' => 'Alamat tidak tersedia',
                'deskripsi' => 'Deskripsi instansi Badan Penanggulangan Bencana Daerah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Pengelola Keuangan dan Aset Daerah',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Badan Pengelola Keuangan dan Aset Daerah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Pengelola Pajak dan Restribusi Daerah',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Badan Pengelola Pajak dan Restribusi Daerah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Kepegawaian dan Diklat',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Badan Kepegawaian dan Diklat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Badan Penelitian dan Pengembangan',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Badan Penelitian dan Pengembangan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Pendidikan',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Pendidikan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Kesehatan',
                'telepon' => 'N/A',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Kesehatan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Perhubungan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Perhubungan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Komunikasi dan Informatika',
                'telepon' => '(0727) 321178',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Komunikasi dan Informatika.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Koperasi, Usaha Kecil dan Menengah',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Koperasi, Usaha Kecil dan Menengah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Penanaman Modal dan Pelayanan Perizinan Terpadu Satu Pintu',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Jl. Trans Sumatra-Stadion Jati Rukun, Kel. Way Lubuk, Kec. Kalianda Kab. Lampung Selatan 35551',
                'deskripsi' => 'Deskripsi instansi Dinas Penanaman Modal dan Pelayanan Perizinan Terpadu Satu Pintu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Kepemudaan dan Olahraga',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Kepemudaan dan Olahraga.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Perpustakaan dan Kearsipan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Alamat instansi Dinas Perpustakaan dan Kearsipan.',
                'deskripsi' => 'Deskripsi instansi Dinas Perpustakaan dan Kearsipan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Perikanan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Perikanan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Pariwisata dan Kebudayaan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Alamat instansi Dinas Pariwisata dan Kebudayaan.',
                'deskripsi' => 'Deskripsi instansi Dinas Pariwisata dan Kebudayaan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Tanaman Pangan, Hortikultura dan Perkebunan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Alamat instansi Dinas Tanaman Pangan, Hortikultura dan Perkebunan.',
                'deskripsi' => 'Deskripsi instansi Dinas Tanaman Pangan, Hortikultura dan Perkebunan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Peternakan dan Kesehatan Hewan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Alamat instansi Dinas Peternakan dan Kesehatan Hewan.',
                'deskripsi' => 'Deskripsi instansi Dinas Peternakan dan Kesehatan Hewan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Perdagangan dan Perindustrian',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Alamat instansi Dinas Perdagangan dan Perindustrian.',
                'deskripsi' => 'Deskripsi instansi Dinas Perdagangan dan Perindustrian.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Satuan Polisi Pamong Praja',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Alamat instansi Satuan Polisi Pamong Praja.',
                'deskripsi' => 'Deskripsi instansi Satuan Polisi Pamong Praja.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dinas Pemadam Kebakaran dan Penyelamatan',
                'telepon' => '(0727) xxxxxx',
                'alamat' => 'Jalan Mustafa Kemal, Kel. Way Urang, Kec. Kalianda, Kab. Lampung Selatan, 35513',
                'deskripsi' => 'Deskripsi instansi Dinas Pemadam Kebakaran dan Penyelamatan.',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('instansi')->insert($dataInstansi);
    }
}
